-- ---------------------   << EVENTOS  >>   ---------------------
--
--                    SCRIPT DE EXCLUSÃO (DML)
-- 
-- Data Criacao ...........: 07/06/2024
-- Autor(es) ..............: Pedro H. Silva e Sabrina C. Berno
-- Banco de Dados .........: MySQL
-- Banco de Dados(nome) ...: TF2
-- 
-- 
-- PROJETO => 01 Base de Dados
--         => 25 Tabelas
-- 
-- -----------------------------------------------------------------

use TF2;

-- Excluir as tabelas da base de dados TF2
DROP TABLE IF EXISTS CONTRATO;
DROP TABLE IF EXISTS comete;
DROP TABLE IF EXISTS trabalha;
DROP TABLE IF EXISTS FICHADO;
DROP TABLE IF EXISTS FREELANCER;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS EMPRESA;
DROP TABLE IF EXISTS PESSOAFISICA;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS ALUGUELDECORACAO_aluga;
DROP TABLE IF EXISTS PARCELA;
DROP TABLE IF EXISTS PAGAMENTO;
DROP TABLE IF EXISTS EVENTO;
DROP TABLE IF EXISTS NOTAFISCAL;
DROP TABLE IF EXISTS composto;
DROP TABLE IF EXISTS BUFFET;
DROP TABLE IF EXISTS FORNECEDOR;
DROP TABLE IF EXISTS CARGO;
DROP TABLE IF EXISTS INGREDIENTE;
DROP TABLE IF EXISTS INFRACAO;
DROP TABLE IF EXISTS ENDERECO;
DROP TABLE IF EXISTS FORMAPAGAMENTO;
DROP TABLE IF EXISTS ITEMBUFFET;
DROP TABLE IF EXISTS ITEMDECORACAO;
DROP TABLE IF EXISTS TIPOFESTA;
